/// A project (mirrors the backend `projects` model). The PO number is generated by the
/// backend at creation; `supervisorId` is null until a supervisor is assigned.
class Project {
  const Project({
    required this.id,
    required this.particular,
    required this.clientName,
    required this.date,
    required this.po,
    required this.supervisorId,
    required this.status,
    required this.createdAt,
    this.supervisorName,
  });

  factory Project.fromJson(Map<String, dynamic> json) => Project(
        id: json['id'] as String,
        particular: json['particular'] as String,
        clientName: json['clientName'] as String,
        date: json['date'] as String,
        po: json['po'] as String,
        supervisorId: json['supervisorId'] as String?,
        status: json['status'] as String,
        createdAt: json['createdAt'] as String,
        supervisorName: json['supervisorName'] as String?,
      );

  final String id;
  final String particular;
  final String clientName;
  final String date;
  final String po;
  final String? supervisorId;
  final String status; // 'active' | 'completed'
  final String createdAt;

  /// Assigned supervisor's display name, resolved by the backend. Null when unassigned
  /// or absent from the response (e.g. the create response).
  final String? supervisorName;

  bool get isAssigned => supervisorId != null;
}
